"""empty message

Revision ID: 9e4dd5c45350
Revises: a69592f4be7b
Create Date: 2021-06-09 15:36:40.947201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4dd5c45350'
down_revision = 'a69592f4be7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('new_field', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'new_field')
    # ### end Alembic commands ###
