"""empty message

Revision ID: a69592f4be7b
Revises: 5be702cf586e
Create Date: 2021-06-09 15:35:16.777424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a69592f4be7b'
down_revision = '5be702cf586e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('new_field', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'new_field')
    # ### end Alembic commands ###
